[2024-11-02T21:57:45.683+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/airflow.py
[2024-11-02T21:57:45.684+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T21:57:45.685+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:57:45.685+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T21:57:45.690+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:57:45.687+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'configuration'?
[2024-11-02T21:57:45.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T21:57:45.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.045 seconds
[2024-11-02T21:58:45.538+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/airflow.py
[2024-11-02T21:58:45.543+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T21:58:45.552+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:58:45.551+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T21:58:45.620+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:58:45.609+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'configuration'?
[2024-11-02T21:58:45.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T21:58:45.680+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.176 seconds
[2024-11-02T21:59:16.641+0000] {processor.py:161} INFO - Started process (PID=75) to work on /opt/airflow/dags/airflow.py
[2024-11-02T21:59:16.681+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T21:59:16.689+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:59:16.688+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T21:59:16.707+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:59:16.701+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'configuration'?
[2024-11-02T21:59:16.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T21:59:16.803+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.182 seconds
[2024-11-02T21:59:47.711+0000] {processor.py:161} INFO - Started process (PID=82) to work on /opt/airflow/dags/airflow.py
[2024-11-02T21:59:47.722+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T21:59:47.730+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:59:47.729+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T21:59:47.747+0000] {logging_mixin.py:188} INFO - [2024-11-02T21:59:47.739+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'configuration'?
[2024-11-02T21:59:47.755+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T21:59:47.830+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.147 seconds
[2024-11-02T22:00:18.756+0000] {processor.py:161} INFO - Started process (PID=89) to work on /opt/airflow/dags/airflow.py
[2024-11-02T22:00:18.770+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/airflow.py for tasks to queue
[2024-11-02T22:00:18.773+0000] {logging_mixin.py:188} INFO - [2024-11-02T22:00:18.772+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/airflow.py
[2024-11-02T22:00:18.777+0000] {logging_mixin.py:188} INFO - [2024-11-02T22:00:18.775+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/airflow.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/airflow.py", line 3, in <module>
    from airflow import configurations as conf
ImportError: cannot import name 'configurations' from 'airflow' (/home/airflow/.local/lib/python3.12/site-packages/airflow/__init__.py). Did you mean: 'configuration'?
[2024-11-02T22:00:18.778+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/airflow.py
[2024-11-02T22:00:18.808+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/airflow.py took 0.058 seconds
